/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.sp.GastroMundo.view;

import br.senac.sp.GastroMundo.Extras.CalculaCPF;
import br.senac.sp.GastroMundo.dao.ConnectionFactory;
import br.senac.sp.GastroMundo.dao.LoginDAO;
import br.senac.sp.GastroMundo.modelo.ModeloCadastro;
import javax.swing.ImageIcon;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Casa
 */
public class Cadastro extends javax.swing.JFrame {
    
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblSenha2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setText("Usuario: ");
        lblEmail.setToolTipText("");
        lblEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 80, 50));

        txtNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 320, 50));

        lblCPF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCPF.setText("CPF:");
        getContentPane().add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 50, 30));

        txtCpf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 320, 50));

        lblSenha2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSenha2.setText("Senha:");
        getContentPane().add(lblSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 60, 30));

        txtSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 320, 50));

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 160, 50));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/TelaDeLogin.jpg"))); // NOI18N
        lblBackground.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lblBackgroundComponentResized(evt);
            }
        });
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 576, 849));

        setSize(new java.awt.Dimension(592, 867));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackgroundComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblBackgroundComponentResized
        ImageIcon icon = new ImageIcon(getClass().getResource("/META-INF/TelaDeLogin.jpg"));
        icon.setImage(icon.getImage().getScaledInstance(lblBackground.getWidth(), lblBackground.getHeight(), 0));
        lblBackground.setIcon(icon);
    }//GEN-LAST:event_lblBackgroundComponentResized

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        ModeloCadastro cadastro = new ModeloCadastro();
        
        String cpf = txtCpf.getText();
        CalculaCPF a = new CalculaCPF();
        if(a.validarCPF(cpf)== false){
            new Login().setVisible(true);
        }else{
            cadastro.setNome(txtNome.getText());
            cadastro.setSenha(txtSenha.getText());
            cadastro.setCpf(cpf);
            try {
                LoginDAO b = new LoginDAO(ConnectionFactory.getConexao());
                b.inserir(cadastro);
                new Menu().setVisible(true);
            } catch (SQLException ex) {
                //Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
            txtNome.setText("");
            txtSenha.setText("");
            txtCpf.setText("");
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSenha2;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
