/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.sp.GastroMundo.view;

import javax.swing.ImageIcon;

/**
 *
 * @author Casa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuBrasil = new javax.swing.JMenuItem();
        mnuItalia = new javax.swing.JMenuItem();
        mnuMexico = new javax.swing.JMenuItem();
        mnuJapao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/TelaPrincipal.jpg"))); // NOI18N
        lblBackground.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lblBackgroundComponentResized(evt);
            }
        });
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1267, 724));

        Menu.setText("Menu");

        jMenu3.setText("Cardápios");

        mnuBrasil.setText("Comida Brasileira");
        mnuBrasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBrasilActionPerformed(evt);
            }
        });
        jMenu3.add(mnuBrasil);

        mnuItalia.setText("Comida Italiana");
        mnuItalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItaliaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItalia);

        mnuMexico.setText("Comida Mexicana");
        mnuMexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMexicoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMexico);

        mnuJapao.setText("Comida Japonesa");
        mnuJapao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuJapaoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuJapao);

        Menu.add(jMenu3);

        jMenuBar1.add(Menu);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1283, 732));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackgroundComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblBackgroundComponentResized
            ImageIcon icon = new ImageIcon(getClass().getResource("/META-INF/TelaPrincipal.jpg"));
            icon.setImage(icon.getImage().getScaledInstance(lblBackground.getWidth(), lblBackground.getHeight(), 0));
            lblBackground.setIcon(icon);
    }//GEN-LAST:event_lblBackgroundComponentResized

    private void mnuBrasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBrasilActionPerformed
        new ComidaBrasileira().setVisible(true);
    }//GEN-LAST:event_mnuBrasilActionPerformed

    private void mnuItaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItaliaActionPerformed
       new ComidaItaliana().setVisible(true);
    }//GEN-LAST:event_mnuItaliaActionPerformed

    private void mnuMexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMexicoActionPerformed
        new ComidaMexicana().setVisible(true);
    }//GEN-LAST:event_mnuMexicoActionPerformed

    private void mnuJapaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuJapaoActionPerformed
        new ComidaJaponesa().setVisible(true);
    }//GEN-LAST:event_mnuJapaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JMenuItem mnuBrasil;
    private javax.swing.JMenuItem mnuItalia;
    private javax.swing.JMenuItem mnuJapao;
    private javax.swing.JMenuItem mnuMexico;
    // End of variables declaration//GEN-END:variables
}
