/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.sp.GastroMundo.view;

/**
 *
 * @author henri
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbPizza = new javax.swing.JLabel();
        btnPizza = new javax.swing.JButton();
        jlbPizza1 = new javax.swing.JLabel();
        btnNachos = new javax.swing.JButton();
        jlbNachos = new javax.swing.JLabel();
        btnSushi = new javax.swing.JButton();
        jlbPizza3 = new javax.swing.JLabel();
        btnFeijao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEnviarPedido1 = new javax.swing.JButton();
        btnEnviarPedido = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jblfull = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jlbPizza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbPizza.setText("Sushi");
        getContentPane().add(jlbPizza);
        jlbPizza.setBounds(560, 80, 120, 20);

        btnPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/NewPizza.jpg"))); // NOI18N
        btnPizza.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(btnPizza);
        btnPizza.setBounds(100, 100, 130, 90);

        jlbPizza1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbPizza1.setText(" Pizza Marguerita");
        getContentPane().add(jlbPizza1);
        jlbPizza1.setBounds(100, 80, 120, 20);

        btnNachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/New  Nachos.jpg"))); // NOI18N
        btnNachos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(btnNachos);
        btnNachos.setBounds(250, 100, 130, 90);

        jlbNachos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbNachos.setText("Nachos Mexicano");
        getContentPane().add(jlbNachos);
        jlbNachos.setBounds(250, 80, 120, 20);

        btnSushi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/New Sushi.jpg"))); // NOI18N
        btnSushi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSushiActionPerformed(evt);
            }
        });
        getContentPane().add(btnSushi);
        btnSushi.setBounds(560, 100, 130, 90);

        jlbPizza3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbPizza3.setText("Feijoada");
        getContentPane().add(jlbPizza3);
        jlbPizza3.setBounds(410, 80, 120, 20);

        btnFeijao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/New Feijoada.jpg"))); // NOI18N
        btnFeijao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(btnFeijao);
        btnFeijao.setBounds(410, 100, 130, 90);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("R$ 35,00");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 200, 130, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("R$ 56,60");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 200, 130, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("R$ 39,90");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 200, 130, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("R$ 40,00");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 200, 130, 20);

        btnEnviarPedido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviarPedido1.setText("Alterar");
        btnEnviarPedido1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviarPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPedido1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarPedido1);
        btnEnviarPedido1.setBounds(310, 660, 120, 30);

        btnEnviarPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviarPedido.setText("Enviar");
        btnEnviarPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarPedido);
        btnEnviarPedido.setBounds(150, 660, 120, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Excluir");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 660, 120, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pedido", "Prato", "Qtd", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 250, 456, 406);

        jblfull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Pedidos GastroMundo (1).png"))); // NOI18N
        getContentPane().add(jblfull);
        jblfull.setBounds(10, 0, 760, 970);

        setSize(new java.awt.Dimension(771, 980));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSushiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSushiActionPerformed

    private void btnEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarPedidoActionPerformed

    private void btnEnviarPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarPedido1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarPedido;
    private javax.swing.JButton btnEnviarPedido1;
    private javax.swing.JButton btnFeijao;
    private javax.swing.JButton btnNachos;
    private javax.swing.JButton btnPizza;
    private javax.swing.JButton btnSushi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jblfull;
    private javax.swing.JLabel jlbNachos;
    private javax.swing.JLabel jlbPizza;
    private javax.swing.JLabel jlbPizza1;
    private javax.swing.JLabel jlbPizza3;
    // End of variables declaration//GEN-END:variables
}
